name: gallery
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/Montserrat-SemiBold.ttf
          weight: 600
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-SemiBold.ttf
          weight: 600
        - asset: fonts/Oswald-Medium.ttf
          weight: 500
